//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sverge.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sverge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; not found or not readable..
        /// </summary>
        public static string App_NewTab_DirectoryNotFound {
            get {
                return ResourceManager.GetString("App_NewTab_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during opening new diff.
        /// </summary>
        public static string App_NewTab_ErrorArguments {
            get {
                return ResourceManager.GetString("App_NewTab_ErrorArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of arguments must be 2 or 3..
        /// </summary>
        public static string App_NewTab_ErrorArgumentsNumberText {
            get {
                return ResourceManager.GetString("App_NewTab_ErrorArgumentsNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; not found or not readable..
        /// </summary>
        public static string App_NewTab_FileNotFound {
            get {
                return ResourceManager.GetString("App_NewTab_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not mix folders and files together as arguments..
        /// </summary>
        public static string App_NewTab_MixingFilesAndFolders {
            get {
                return ResourceManager.GetString("App_NewTab_MixingFilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no special manager for viewing this diff..
        /// </summary>
        public static string App_NoWindowDefined {
            get {
                return ResourceManager.GetString("App_NoWindowDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during parsing the settings.
        /// </summary>
        public static string App_OnStartup_ErrorParsingSettings {
            get {
                return ResourceManager.GetString("App_OnStartup_ErrorParsingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This argument option has not been found &apos;{0}&apos;.
        /// </summary>
        public static string App_OnStartup_InvalidSettingsValue {
            get {
                return ResourceManager.GetString("App_OnStartup_InvalidSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor &apos;{0}&apos; could not be loaded because of a priority collision..
        /// </summary>
        public static string App_OnStartup_ProcessorCollision {
            get {
                return ResourceManager.GetString("App_OnStartup_ProcessorCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value for given option is invalid &apos;{0}&apos;.
        /// </summary>
        public static string App_OnStartup_UnknownSettingsValue {
            get {
                return ResourceManager.GetString("App_OnStartup_UnknownSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sverge - diff &amp; merge tool .
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file at this location..
        /// </summary>
        public static string Diff_No_File_At_Location {
            get {
                return ResourceManager.GetString("Diff_No_File_At_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current comparison.
        /// </summary>
        public static string Menu_CloseComparison {
            get {
                return ResourceManager.GetString("Menu_CloseComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new comparison.
        /// </summary>
        public static string Menu_NewComparison {
            get {
                return ResourceManager.GetString("Menu_NewComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory....
        /// </summary>
        public static string NewWindow_Button_DirectoryDialog {
            get {
                return ResourceManager.GetString("NewWindow_Button_DirectoryDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        public static string NewWindow_Button_FileDialog {
            get {
                return ResourceManager.GetString("NewWindow_Button_FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NewWindow_Button_Open {
            get {
                return ResourceManager.GetString("NewWindow_Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base (optional).
        /// </summary>
        public static string NewWindow_Label_Base {
            get {
                return ResourceManager.GetString("NewWindow_Label_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string NewWindow_Label_Local {
            get {
                return ResourceManager.GetString("NewWindow_Label_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote.
        /// </summary>
        public static string NewWindow_Label_Remote {
            get {
                return ResourceManager.GetString("NewWindow_Label_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open files/directories for diffing.
        /// </summary>
        public static string NewWindow_Title {
            get {
                return ResourceManager.GetString("NewWindow_Title", resourceCulture);
            }
        }
    }
}
