//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Sverge.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Sverge.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during opening new diff.
        /// </summary>
        public static string App_NewTab_ErrorArgumentsNumber {
            get {
                return ResourceManager.GetString("App_NewTab_ErrorArgumentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of arguments must be 2 or 3..
        /// </summary>
        public static string App_NewTab_ErrorArgumentsNumberText {
            get {
                return ResourceManager.GetString("App_NewTab_ErrorArgumentsNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there is no special window for viewing this diff..
        /// </summary>
        public static string App_NoWindowDefined {
            get {
                return ResourceManager.GetString("App_NoWindowDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during parsing the settings.
        /// </summary>
        public static string App_OnStartup_ErrorParsingSettings {
            get {
                return ResourceManager.GetString("App_OnStartup_ErrorParsingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This argument option has not been found &apos;{0}&apos;.
        /// </summary>
        public static string App_OnStartup_InvalidSettingsValue {
            get {
                return ResourceManager.GetString("App_OnStartup_InvalidSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor &apos;{0}&apos; could not be loaded because of a priority collision..
        /// </summary>
        public static string App_OnStartup_ProcessorCollision {
            get {
                return ResourceManager.GetString("App_OnStartup_ProcessorCollision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value for given option is invalid &apos;{0}&apos;.
        /// </summary>
        public static string App_OnStartup_UnknownSettingsValue {
            get {
                return ResourceManager.GetString("App_OnStartup_UnknownSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file at this location..
        /// </summary>
        public static string Diff_No_File_At_Location {
            get {
                return ResourceManager.GetString("Diff_No_File_At_Location", resourceCulture);
            }
        }
    }
}
