//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiffWindows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiffWindows.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file at this location..
        /// </summary>
        public static string Diff_No_File_At_Location {
            get {
                return ResourceManager.GetString("Diff_No_File_At_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base file different.
        /// </summary>
        public static string Differences_BaseDifferent {
            get {
                return ResourceManager.GetString("Differences_BaseDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base file missing.
        /// </summary>
        public static string Differences_BaseMissing {
            get {
                return ResourceManager.GetString("Differences_BaseMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only on base.
        /// </summary>
        public static string Differences_BaseOnly {
            get {
                return ResourceManager.GetString("Differences_BaseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files differ.
        /// </summary>
        public static string Differences_FilesDifferent {
            get {
                return ResourceManager.GetString("Differences_FilesDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file deleted.
        /// </summary>
        public static string Differences_LocalDeleted {
            get {
                return ResourceManager.GetString("Differences_LocalDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file different.
        /// </summary>
        public static string Differences_LocalDifferent {
            get {
                return ResourceManager.GetString("Differences_LocalDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file missing.
        /// </summary>
        public static string Differences_LocalMissing {
            get {
                return ResourceManager.GetString("Differences_LocalMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only on local.
        /// </summary>
        public static string Differences_LocalOnly {
            get {
                return ResourceManager.GetString("Differences_LocalOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote file deleted.
        /// </summary>
        public static string Differences_RemoteDeleted {
            get {
                return ResourceManager.GetString("Differences_RemoteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote file different.
        /// </summary>
        public static string Differences_RemoteDifferent {
            get {
                return ResourceManager.GetString("Differences_RemoteDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote file missing.
        /// </summary>
        public static string Differences_RemoteMissing {
            get {
                return ResourceManager.GetString("Differences_RemoteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only on remote.
        /// </summary>
        public static string Differences_RemoteOnly {
            get {
                return ResourceManager.GetString("Differences_RemoteOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Menu_Changes {
            get {
                return ResourceManager.GetString("Menu_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Menu_Changes_Next {
            get {
                return ResourceManager.GetString("Menu_Changes_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Menu_Changes_Previous {
            get {
                return ResourceManager.GetString("Menu_Changes_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Menu_Merge {
            get {
                return ResourceManager.GetString("Menu_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge to base.
        /// </summary>
        public static string Menu_Merge_Merge {
            get {
                return ResourceManager.GetString("Menu_Merge_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next conflict.
        /// </summary>
        public static string Menu_Merge_Next {
            get {
                return ResourceManager.GetString("Menu_Merge_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous conflict.
        /// </summary>
        public static string Menu_Merge_Previous {
            get {
                return ResourceManager.GetString("Menu_Merge_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use base version.
        /// </summary>
        public static string Menu_Merge_UseBase {
            get {
                return ResourceManager.GetString("Menu_Merge_UseBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use local version.
        /// </summary>
        public static string Menu_Merge_UseLocal {
            get {
                return ResourceManager.GetString("Menu_Merge_UseLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use remote version.
        /// </summary>
        public static string Menu_Merge_UseRemote {
            get {
                return ResourceManager.GetString("Menu_Merge_UseRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unresolved conflicts.
        /// </summary>
        public static string Popup_Conflicts {
            get {
                return ResourceManager.GetString("Popup_Conflicts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resolve the remaining conflicts before merging.
        /// </summary>
        public static string Popup_Conflicts_Resolve {
            get {
                return ResourceManager.GetString("Popup_Conflicts_Resolve", resourceCulture);
            }
        }
    }
}
